import "~/styles/globals.css";

import { type Metadata } from "next";
import { Raleway,Rasa,Dancing_Script } from "next/font/google";
import { Analytics } from "@vercel/analytics/next"
import { Providers } from "./providers";
import { TRPCReactProvider } from "~/trpc/react";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--font-raleway",
});

const rasa = Rasa({
  subsets: ["latin"],
  variable: "--font-rasa",
});

const dancing_script = Dancing_Script({
  subsets: ["latin"],
  variable: "--font-dancing-script",
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${raleway.className} ${rasa.className} ${dancing_script.className}`} suppressHydrationWarning>
      <body>
        <Providers>
          <TRPCReactProvider>
            {children}
            <Analytics />
          </TRPCReactProvider>
        </Providers>
      </body>
    </html>
  );
}
